### ISSUE TITLE
Showing the blog title on the index page

### ISSUE THREAD

**Issue by jordanisip** [HiDeoo/starlight-blog#110]
### Is your feature request related to a problem?

Thanks so much for the plugin. I'd love a configuration to use the blog title on the index page above all of the other posts to provide some context.

Does anyone happen to know of a workaround to add this? Maybe a component override or something? Appreciate the help.

### Describe the solution you'd like

A configuration to use the blog title on the index page.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

Interesting, I don't think this is a feedback I've got before but definitely interesting. I think I'd like to get more feedback about this before pulling the trigger on a configuration option or potentially an even more elaborate solution like overrides.

In the meantime, a workaround should be using [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) in Starlight and using the following CSS:

```css
.content-panel:first-of-type:has(+ .content-panel .posts) {
  display: block;
}

.content-panel:nth-of-type(2):has(.posts) {
  border-top: 1px solid var(--sl-color-hairline);
}
```
