### ISSUE TITLE
Auto excerpt - instead of frontmatter

### ISSUE THREAD

**Issue by haukened** [HiDeoo/starlight-blog#142]
### Is your feature request related to a problem?

I'm always a little frustrated having to write things twice, the blog post, and then the excerpt. It seems like a lot of duplicated work.

### Describe the solution you'd like

On other blogging platforms (docusaurus, et. al.) you define a place in the article using some kind of separator, and the excerpt/preview truncates at the spot you define. This means you don't have to have an excerpt / summary / preview frontmatter option, you just add the truncation point wherever you'd like.

### Describe alternatives you've considered

Having ChatGPT write me a summary because I'm tired of writing... haha.

### Additional Context

Here's from the [docusaurus blog documentation](https://docusaurus.io/docs/blog#adding-posts)

```
---
title: Welcome Docusaurus
description: This is my first post on Docusaurus.
slug: welcome-docusaurus-v2
authors:
  - name: Joel Marcey
    title: Co-creator of Docusaurus 1
    url: https://github.com/JoelMarcey
    image_url: https://github.com/JoelMarcey.png
    socials:
      x: joelmarcey
      github: JoelMarcey
  - name: Sébastien Lorber
    title: Docusaurus maintainer
    url: https://sebastienlorber.com
    image_url: https://github.com/slorber.png
    socials:
      x: sebastienlorber
      github: slorber
tags: [hello, docusaurus-v2]
image: https://i.imgur.com/mErPwqL.png
hide_table_of_contents: false
---

Welcome to this blog. This blog is created with [**Docusaurus 2**](https://docusaurus.io/).

<!-- truncate -->

This is my first post on Docusaurus 2.

A whole bunch of exploration to follow.
```
